---
title: "Course Alumni"
---

A major aim of this course is to help students display their newfound data science skills to gain tangible professional benefits. This is why the GitHub presence assignment (rubric [here](https://njlyon0.github.io/teach_r-for-biologists/rubrics/rubric_github.html)) and the function tutorial assignment (rubric [here](https://njlyon0.github.io/teach_r-for-biologists/rubrics/rubric_tutorials.html)) are given so much emphasis in the course schedule and in their point values to those taking the course for credit at their institution. In service of this goal, this page was created to allow interested students to have their GitHub profiles and portfolios demonstrated to anyone who visits this course's page.

I present students with the _option_ of promoting their GitHub selves here at the end of the course and use an 'opt in' method so only those students who are comfortable sharing are included below. The first offering of this course (2023) predates this course website so none of that cohort is included here.

## Alumni Directory

Below are the course alumni and links to their GitHub profiles where you can find examples of their work! In particular, **check out their "portfolio" repositories!** Alums are in alphabetical order by last name and each tabset panel corresponds to an institution where I've taught this course.

:::{.panel-tabset}
### Stonehill College

| A-L | M-Z|
|:---:|:---:|
| Colton Burkhart -- {{< fa brands github >}} [cgb913](https://github.com/cgb913) | Matthew King -- {{< fa brands github >}} [matthewking7](https://github.com/matthewking7) |
| Juliana Dawood -- {{< fa brands github >}} [jdawood04](https://github.com/jdawood04) | Anna Varholak -- {{< fa brands github >}} [avarholak](https://github.com/avarholak) |

:::