---
title: "Homework Answer Keys"
format:
  html: default
---

## Keys Overview

I've designed a (short) homework assignment to be completed after each week's lecture and lab slides have been covered. These assignments are generally due at midnight the day before the following week's lecture. They are individually 'low stakes' assignments but collectively they are an appreciable part of a student's overall grade and so should not be neglected. More importantly, they are a valuable chance for students to practice the skills they acquire during in-class discussions and practice sessions. 

In code contexts there is almost always more than one way of accomplishing a given task but I've taken the liberty of drafting "answer keys" for each week's homework. These keys are example assignments that would earn maximum points according to the rubrics (embedded at the end of each week's home page).

## Accessing Keys

### Educators

Educators can access the keys in a private GitHub repository (linked [here](https://github.com/njlyon0/teach_r-for-biologists-keys/tree/main)) though you will need to [contact me](https://njlyon0.github.io/) so that I can give you access.

### Students

Students can access the answer keys [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ) instead.
