---
title: "Function Tutorials Rubric"
format:
  html: default
---

## Learning Objective(s)

Upon completion of these assignments, students will be able to:

- **Explain** the proper syntax and use of R functions
- **Communicate** effectively to an audience of interested non-specialists
- **Apply** feedback on an assignment to a successful revision
- **Reflect** on the process of revising a presentation based on constructively critical feedback

## Assignment Due Date(s)

This assignment is split into several drafts and pre-draft work each with their own due date. See below for specific dates for each component part:

-   Look through CRAN for 7-10 potential functions -- due before Lecture #4 at midnight

    -   7-10 so you have alternates if others pick the functions you had in mind

-   Pick 3 functions for your assignment -- done *during class* in Lecture #4

    -   Order for choosing will be random
    -   I.e., One by one, everyone in class picks first function, then re-randomize for second function, and again for third

-   Submit Quarto file (.qmd) of function tutorials (Draft #1) -- due day before Lab #5 at midnight

-   Present tutorials (Draft #1) -- done during class in Lab #5

    -   You will also submit your peer reviews for your peers' tutorials during lab this day

-   Submit Quarto file of function tutorials (Draft #2) -- due day before Lab #7 at midnight

-   Present tutorials (Draft #2) -- done *during class* in Lab #7

    -   Again, you'll submit peer reviews of others' revised presentations today

-   *OPTIONAL:* Submit Quarto file of function tutorials (Draft #3) -- due day before Lab #8 at midnight

    -   Fully optional, see below for more information

## Assignment Description

This assignment is built to give you real-world experience with teaching yourself a new tool and then relating that knowledge to team members in an accessible and reproducible format. The opportunity for revision according to constructively critical and positive feedback is also an integral facet of virtually all career paths but especially so in data science. The two required drafts (and optional third draft) will follow the rubrics included below; note that the first and second/third draft use different rubrics so double check that you are using the correct guidelines as you work on both assignments.

## Draft #1 Rubric

This assignment is worth thirty (30) points; this is equivalent to roughly 12% of your overall course grade. Your score is divided between the report overall (worth 6 points) and the tutorials for each function (worth 8 points each; 24 total). An overall score of 0 points is only possible with no submission or submission is 10 days late.

Because this assignment is a tutorial of three functions, the points for the function tutorial component (see below) are earned independently for each function. The total points for this draft will be equal to your score in the "report overall" component plus the score earned for each function according to the "function tutorial" part of the rubric below.

| Component | Points Earned | Standard  |
|:--------------------:|:--------------:|:--------------------------------------------------------------------------------------------------------|
|  Report Overall   | 6 | \- Report is a well-formatted Quarto file that knits to HTML or PDF </br> - Relevant headers and sub-headings divide the three functions' sections in the document </br> - Text gives excellent context for embedded code chunks </br> - Few or no grammatical issues in text |
|  Report Overall   | 4 | \- Report is a Quarto file but formatting is imprecise </br> - Headers and sub-headings are limited or incompletely used </br> - Text gives some context for code chunks but is incomplete for full understanding of the functions </br> - Moderate grammatical issues in text but still understandable |
|  Report Overall   | 2 | \- Report is not a Quarto file </br> - Headers and sub-headings are either not used at all or are so rare as to be functionally absent </br> - Text does not provide adequate context for code chunks or code chunks are completely absent </br> - Grammatical issues severe enough to impede understanding |
| Function Tutorial | 8 | \- Function purpose is clearly explained by both plain language text and embedded code chunks </br> - Code chunks adhere to reproducibility best practices (e.g., makes effective use of comments and all function arguments are defined) </br> - Most / all arguments are defined in plain text </br> - Code can be run by instructor with clean environment without errors </br> - Package that exports this function is clearly indicated |
| Function Tutorial | 6 | \- Function purpose is explained but explanation is not completely clear and/or areas of confusion exist </br> - Code chunks adhere to some reproducibility best practices but implementation is inconsistent </br> - Some arguments are defined in plain text but others are not explained </br> - Code can be run by instructor with only minor errors </br> - Package that exports this function is indicated but could be clearer |
| Function Tutorial | 4 | \- Function explanation is minimal and significant unexplained areas exist </br> - Code chunks do not adhere to reproducibility guidelines </br> - Few arguments are defined in the text or code </br> - Package may or may not be indicated </br> - Code cannot be run by instructor due to major errors |
| Function Tutorial | 2 | \- Explanation is so limited as to be unhelpful to target audience </br> - Either no code chunks at all or major errors prevent running of embedded code </br> - Package may or may not be indicated |
| Total | 0 | No submission OR submission is more than 10 days late |

"Function Tutorial" component assessed for *each* function <u>independently</u>.

## Draft #2 Rubric

This assignment is worth forty (40) points; this is equivalent to roughly 16% of your overall course grade. The revision is scored based on four components:

1.  Report Overall (same rubric as Draft #1)

2.  Function Tutorial (same rubric as Draft #1)

3.  Revision Implementation (7 points)

    - Based on (1) comparisons between your first draft and presentation and your revised draft and presentation as well as (2) how extensively you integrate changes based on peer feedback

4.  Revision Response (3 pts)

    - Based on a short document where you explain what changes you made from the previous draft and provide rationale for any feedback that did not cause you to make changes (i.e., why certain pieces of feedback were ignored if any).
    - Should be submitted as a separate document

| Component | Points Earned | Standard |
|:--------------------:|:--------------:|:--------------------------------------------------------------------------------------------------------|
| Revision Implementation | 7 | \- Refined report content according to the majority of positive and constructively critical feedback </br> - Presentation style or approach also modified following suggestions from audience at previous presentation |
| Revision Implementation | 5 | \- Revised report content according to some feedback but other major feedback ignored / left unaddressed </br> - Presentation approach likewise changed from first attempt but some important pieces of feedback did not result in changes to presentation |
| Revision Implementation | 3 | \- Report content not substantially revised from first draft </br> - Presentation likewise mostly unchanged from first attempt |
| Revision Implementation | 1 | \- Changes between drafts (of report / presentation) not substantial enough for differences to be clear |
|    Revision Response    | 3 | \- Clearly identifies major changes (at least three) made from first draft and which feedback those changes address </br> - Provides strong rationale for feedback that did not result in changes to the report / presentation </br> - Includes short (2-3 sentence) reflection on what was learned during the revision process |
|    Revision Response    | 2 | \- Identification of changes made from first draft unclear / vague </br> - Ignored feedback not sufficiently justified </br> - Reflection on personal insights gained from revision process lacks depth |
|    Revision Response    | 1 | \- Response minimal and/or does not include all required components |
|    Total    | 0 | No submission OR submission is more than 10 days late |

## Draft #3 Rubric (*Optional*)

If you'd like, you can revise your second draft according to the feedback you receive from your peers and myself when you present for the second time. If you choose to submit a third draft, it will be evaluated in the same way as the second draft as indicated in the rubric above (so you must also submit a Revision Response).

**Your score on this third draft will replace your score for the second draft!**

If you do submit a third draft, your score can only improve! This is meant to give you another chance to respond to feedback and also--potentially--earn maximum points on this assignment in the event that you missed it by a few points on your second draft.
