---
title: "Course Policies"
format:
  html: default
---

## Attendance

If you get sick, observe a religious holiday unaccounted for by the university's calendar, have to miss class for a job/grad school interview, or simply don't think you can handle class on a given day, please email me as early as possible to let me know you won't be in class with a (brief) explanation. This will help me to share resources we'll cover in class with you and plan for a smaller in-class community while you are out. My hope is that this class will be somewhere you *want* to attend, but I understand that sometimes life happens!

While attendance is neither required nor graded, please do not abuse my sympathy and instead reserve absences for days where you honestly cannot attend. Your presence in and contributions to class are important both to your understanding of the material and the creation and maintenance of an in-class community.

## Late Assignments

Late work will be accepted with a 10% penalty for each day that it is late. You are welcome to submit assignments that are more than 10 days for feedback so that you can improve going forward but assignments submitted that far after the due date will not be worth any points. If you think that you will struggle to meet a particular deadline, come chat with me *as soon as possible* so that we can work out whether a compromise would be possible.

## Zoom Etiquette

If needed, the entirety of this course can be taught virtually so I would like to clarify some expectations I have for that modality. I ***do not*** require that you either have your camera on or unmute yourself to contribute verbally. That said, talking with a room full of muted Zoom panels with cameras turned off makes it difficult for me to know whether I'm successfully engaging you and that you understand the material. Therefore, I really encourage you to have your cameras on and unmute to ask or answer questions as needed.

Regardless of whether you take me up on that, I will make extensive use of the chat and "reactions" feature (i.e., thumbs up, raised hand, etc.) so be ready to engage on those axes whether or not your camera and mic are on for full participation credit (see participation guidelines below).

## Artificial Intelligence

Artificial intelligence (AI) tools are increasingly entering public consciousness. These tools (e.g., ChatGPT, GitHub Copilot, etc.) often market themselves as a mode of increasing efficiency or making code operations easier. While this may or may not be true for experienced programmers, **<u>I strongly discourage the use of AI tools for this class</u>.** I feel this way for two reasons:

1. **I believe shortcuts--like AI--will undercut your learning.** A vital bit of learning any new skill is engaging your problem solving skills to develop an intuition about how concepts fit together. If you overly rely on AI tools you will directly inhibit this process and--in extreme cases--may not be able to accomplish coding tasks in contexts where AI tools are inappropriate (e.g., job interviews, with clients, etc.).

2. **There are ethical considerations around AI that are not well-discussed.** This course is not flexible enough to also be a primer in AI ethics so it is better to just avoid using these tools until you have the chance to educate yourselves and make an informed decision for yourself. If this topic area is of interest to you, I recommend doing a [Google Scholar](https://scholar.google.com/) search for the peer-reviewed articles being published on this topic. Your institution may also offer an ethics or bioethics course (often in the Philosophy department or cross-listed there) if you'd prefer a trained ethicist help you develop formal knowledge in this sphere.

### AI Policy Enforcement Note

I became an educator because I get joy from supporting new learners. I definitely know that I wouldn't be where I am today without some passionate mentors and teachers who believed in me and supported my development in the very first steps of my career. Because of this philosophy, I am not interested in "policing" students. I will not make any attempt to restrict how you use the internet nor will I turn this class into a mini surveillance state in an attempt to prevent the use of AI tools or other forms of "cheating".

**If you find that you are struggling in this course and feel pressured to use AI tools to succeed, <u>please come talk to me so that we can discuss reasonable accommodations for you to succeed under your own power and intellect</u>.**

## Usability, Accessibility, and Design

I am committed to creating a course that is inclusive in its design. If you encounter barriers, please let me know immediately so that we can determine if there is a design adjustment that can be made or if an accommodation might be needed to overcome the limitations of the design. I am always happy to consider creative solutions as long as they do not compromise the intent of the assessment or learning activity. I welcome feedback that will assist me in improving the usability and experience for all students.

## Name, Gender Identity, and/or Gender Expression

The university will provide me with each student's legal name, but I will gladly honor your request to address you by an alternate name. I will also use whichever gender pronouns you identify with. Please advise me of your pronouns and/or chosen name early in the semester so that I may make appropriate changes to my records.

## Respect for your Peers

Group work is a significant part of this course explicitly in some of the assignments as well as implicitly by the collaborative nature of some of these coding tasks. I expect that you will be mutually respectful with one another both in and outside of class time. I will ask you questions during lab and lecture and both places are also an ideal time for you all to ask me questions that you have on course topics & policies. I don't believe that "dumb questions" exist, and I expect that you treat your peers' questions with the respect that your fellow students deserve. Together we will learn more in an environment where we build one another up than we would in one where we fail to support one another.
